Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Security_Lab_Day3.Data;
using Web_Security_Lab_Day3.Repositories;
using Web_Security_Lab_Day3.ViewModels;

namespace Web_Security_Lab_Day3.Controllers
{
    public class RoleController : Controller
    {
        private readonly ApplicationDbContext _context;
        public RoleController(ApplicationDbContext context)
        {            
            _context = context;
        }



        // GET: Role
        public ActionResult Index()
        {
            RoleRepo roleRepo = new RoleRepo(_context);
            return View(roleRepo.GetAllRoles());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RoleVM newRole)
        {

            RoleRepo roleRepo = new RoleRepo(_context);

            bool result = roleRepo.CreateRole(newRole.RoleName);

            if (!result)
            {
                return View(newRole);
            }
            else
            {

                return RedirectToAction("Index");

            }
        }
    }
}

Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web_Security_Lab_Day3.Data;
using Web_Security_Lab_Day3.Models;
using Web_Security_Lab_Day3.Repositories;

namespace Web_Security_Lab_Day3.Controllers
{
    public class ShopController : Controller
    {

        private ApplicationDbContext _context;
        public ShopController(ApplicationDbContext context)
        {
            _context = context;

        }

        public IActionResult Index()
        {
            DbSet<Product> products = _context.Product;
            return View(products);
        }

     
    }
}

Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web_Security_Lab_Day3.Data;
using Web_Security_Lab_Day3.Models;

namespace Web_Security_Lab_Day3.Controllers
{
    public class TransactionsController : Controller
    {

        private ApplicationDbContext _context;
        

        public TransactionsController(ApplicationDbContext context)
        {
            _context = context;
            
        }




        // Home page shows list of items.
        // Item price is set through the ViewBag.
        [Authorize]
        public IActionResult Transactions()
        {
            DbSet<IPN> items = _context.IPNs;

            foreach (var item in items)
            {
                DateTime createDT = Convert.ToDateTime(item.create_time);
                string stringCreateDT = createDT.ToString("dd'/'MM'/'yyyy, HH:mm");
                item.create_time = stringCreateDT;
            }

            return View(items);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_Security_Lab_Day3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_Security_Lab_Day3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid" style="background-color:#26C6DA;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/DeckMaster.png" class="deck-size" alt="deck-master"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                          <li>
                            <a asp-area="" class="nav-link text-dark" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>

                        @{
                            if (User.IsInRole("Manager"))
                            {   
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Transactions">Transactions</a>
                                </li>
                            }
                        }

                        @{if (User.IsInRole("Manager") || User.IsInRole("Admin"))
                        {

                        <li>
                            <a asp-area="" class="nav-link text-dark" asp-controller="UserRole"
                               asp-action="Index">
                                User
                            </a>
                        </li>

                        <li>
                            <a asp-area="" class="nav-link text-dark" asp-controller="Role"
                               asp-action="Index">Roles</a>
                        </li>
                        }}
                      @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Confirmation">Confirmation</a>
                        </li>*@
                      

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Deck-Master
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>